import { EventMedia } from './EventMedia';
import { LivePosition } from './LivePosition';
import { LocationsItem } from './LocationsItem';
import { EventSummary } from './EventSummary';
import { SubEventMaster } from './SubEventMaster';
import { EventLog } from './EventLog';

export class EventDto {
  eventCode!: string;
  idString!: string;
  eventStartDate!: Date;
  eventEndDate!: Date;
  eventDescription!: string;
  vehicleRegistration!: string;
  eventTypeCode!: number;
  tripStartPositionCode!: number;
  tripEndPositionCode!: number;
  tripStartDate!: Date;
  tripEndDate!: Date;
  tripDuration!: number;
  tripDrivingTime!: number;
  tripStandingTime!: number;
  tripDistanceDriven!: number;
  tripMaxSpeed!: number;
  medias!: EventMedia[];
  endLocationName!: string;
  startLocatioName!: string;
  startPositionDetails!: LivePosition;
  endPositionDetails!: LivePosition;
  eventSource!: string;
  shift!: string;
  // SEEING MACHINE DATA
  // SEEING MACHINE DATA
  duration!: number;
  serialNumber!: string;
  contractorName!: string;
  confirmationState!: string;
  detectedDateTime!: Date;
  alarms!: string;
  detectedPositionCode!: string;
  tracking!: string;
  travelDistance!: number;
  stationaryTime!: string;
  bearing!: number;
  tripTime!: Date;
  travel!: string;
  age!: number;
  speed!: number;
  timeIntoShift!: Date;
  gPSCoverage!: number;
  driverName!: string;
  originalCode!: number;
  livePositionsList!: LocationsItem[];
  eventAge!: string;
  eventSummaryLists!: EventSummary[];
  showExamine!: boolean;
  isClassificationAllowed!: boolean;
  isReclassificationAllowed!: boolean;
  isAcknowledged!: boolean;
  suggestedEventTypeCode!: number;
  suggestedEventTypeDescription!: string;
  subEventTypes!: SubEventMaster[];
  suggestedSubEventTypes!: SubEventMaster[];
  duration_in_hours!: number;
  duration_in_minutes!: number;
  duration_in_seconds!: number;
  ageAgo!: string;

  code!: string;
  startDate!: Date;
  endDate!: Date;
  eventStatus!: string;
  eventLog!: EventLog;
  lastSynchDate!: string;
  totalEvents!: number;
  fatigue!: number;
  distraction!: number;
  fov!: number;
  overSpeed!: number;
  harshBrake!: number;
  harshAcceleration!: number;
  overRevving!: number;
  forwardCollisionWarning!: number;
  pedestrianInDangerZone!: number;
  pedestrianInForwardCollisionWarning!: number;
  leftLaneDeparture!: number;
  mobileeye!: number;
  rightLaneDeparture!: number;

  // abu dhabi

  // abu dhabi
  eventsId!: number;
  alarmID!: string;
  alarmName!: string;
  alarmTime!: Date;
  c27Spic!: string;
  c27V!: string;
  c27Wpic!: string;
  c28Back!: string;
  c28Overview!: string;
  carLicense!: string;
  evidenceID!: string;
  evidenceName!: string;
  evidenceType!: string;
  extraInfo!: string;
  lat!: number;
  long!: number;
  fileName!: string;
  legalCode!: string;
  radarKind!: string;
  roadId!: string;
  roadRegion!: string;
  violationDirection!: string;
  violationLane!: string;
  violationTypeID!: string;
  tG_Distance!: string;
  tG_Duration!: string;
  tG_Speed!: string;
  address!: string;
}
